version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wp:
    depends_on:
      - db
    image: wordpress:5.2-php7.1
    volumes:
      - ./wp-themes:/var/www/html/wp-content/themes
      - ./wp-plugins:/var/www/html/wp-content/plugins
    ports:
      - "3000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    container_name: wordpress-dashboard

volumes:
  db_data: {}